spring:
  # database
  # --- rds postgresql db --- #
  datasource:
    url: jdbc:postgresql://database-pionada-ai-poc-13.cuerrc1vwpjd.ap-northeast-2.rds.amazonaws.com:5023/vs_dp_data_service
    username: pionada_ai_poc
    password: pocAiPionada1#
    hikari:
      maximum-pool-size: 4