spring:
  # database
  # --- rds postgresql db --- #
  datasource:
    url: jdbc:postgresql://database-pionada-ai-poc-13.cuerrc1vwpjd.ap-northeast-2.rds.amazonaws.com:5023/vs_dp_data_service
    username: pionada_ai_poc
    password: pocAiPionada1#
    hikari:
      maximum-pool-size: 4



mybatis: # type을 쉽게 쓰기 위해서 dto 패키지를 type-aliaes에 설정
  mapper-locations: /mappers/**/*.xml
  type-aliases-package: visang.showcase.aibackend.dto
  config-location: classpath:mybatis/mybatis-config.xml

# 세션 타임아웃 설정
server:
  servlet:
    session:
      timeout: 1800
      cookie:
        same-site: "none"
        
security:
  jwt:
    token:
      secret-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9eyJzdWIiOiIiLCJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE1MTYyMzkwMjJ9ih1aovtQShabQ7l0cINw4k1fagApg3qLWiB8Kt59Lno
      expire-length: 86400000 # 유효기간 1일